# Parametric Claim Service
server.port=8086
spring.application.name=parametric-claim-service
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.url=jdbc:h2:file:./data/parametric-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

gcul.claims-service.url=http://127.0.0.1:8085
gcul.notification-service.url=http://127.0.0.1:8084
gcul.blockchain-service.url=http://127.0.0.1:8088
gcul.payment-service.url=http://127.0.0.1:8083
