# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.cloud.universalledger.v1 import universalledger_pb2 as google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/cloud/universalledger/v1/universalledger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UniversalLedgerStub:
    """A service for interacting with the Google Cloud Universal Ledger.
    Endpoints are pre-created and managed by Google and cannot
    be modified by users.
    The names of available endpoints will be provided in the public
    documentation.
    An endpoint is a regional resource within a Universal Ledger network.
    Requests sent to an endpoint may be routed to different validators in the
    given network within the given region.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTransaction = channel.unary_unary(
                '/google.cloud.universalledger.v1.UniversalLedger/SubmitTransaction',
                request_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitTransactionRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitTransactionResponse.FromString,
                _registered_method=True)
        self.ListEndpoints = channel.unary_unary(
                '/google.cloud.universalledger.v1.UniversalLedger/ListEndpoints',
                request_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.ListEndpointsRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.ListEndpointsResponse.FromString,
                _registered_method=True)
        self.GetEndpoint = channel.unary_unary(
                '/google.cloud.universalledger.v1.UniversalLedger/GetEndpoint',
                request_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.GetEndpointRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.Endpoint.FromString,
                _registered_method=True)
        self.SubmitOperationalTransaction = channel.unary_unary(
                '/google.cloud.universalledger.v1.UniversalLedger/SubmitOperationalTransaction',
                request_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitOperationalTransactionRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitOperationalTransactionResponse.FromString,
                _registered_method=True)
        self.QueryTransactionState = channel.unary_unary(
                '/google.cloud.universalledger.v1.UniversalLedger/QueryTransactionState',
                request_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryTransactionStateRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryTransactionStateResponse.FromString,
                _registered_method=True)
        self.QueryAccount = channel.unary_unary(
                '/google.cloud.universalledger.v1.UniversalLedger/QueryAccount',
                request_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryAccountRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryAccountResponse.FromString,
                _registered_method=True)


class UniversalLedgerServicer:
    """A service for interacting with the Google Cloud Universal Ledger.
    Endpoints are pre-created and managed by Google and cannot
    be modified by users.
    The names of available endpoints will be provided in the public
    documentation.
    An endpoint is a regional resource within a Universal Ledger network.
    Requests sent to an endpoint may be routed to different validators in the
    given network within the given region.
    """

    def SubmitTransaction(self, request, context):
        """Submits a transaction to the network.
        The request is first validated for basic correctness. If validation fails,
        the request will fail immediately.
        If validation succeeds, this method returns only after the transaction has
        been replicated across a majority of validators in the network, or until
        the request fails.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEndpoints(self, request, context):
        """Lists all endpoints for a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEndpoint(self, request, context):
        """Gets the details of a specific endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitOperationalTransaction(self, request, context):
        """Submits an operational transaction to the network.
        This method returns only after the transaction has been replicated across a
        majority of validators in the network, or if the transaction fails.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTransactionState(self, request, context):
        """Queries the state of a transaction. This method can be called for any
        transaction submitted to the network. The returned transaction details may
        vary between calls, because an endpoint may route requests to different
        validators within the network and region, and the validators may not be at
        the same round ID at any given time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAccount(self, request, context):
        """Queries all the information stored about an account in the network.
        The returned account details may vary between calls, because an
        endpoint may route requests to different validators within the network and
        region, and the validators may not be at the same round ID at any given
        time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UniversalLedgerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTransaction,
                    request_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitTransactionRequest.FromString,
                    response_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitTransactionResponse.SerializeToString,
            ),
            'ListEndpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEndpoints,
                    request_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.ListEndpointsRequest.FromString,
                    response_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.ListEndpointsResponse.SerializeToString,
            ),
            'GetEndpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEndpoint,
                    request_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.GetEndpointRequest.FromString,
                    response_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.Endpoint.SerializeToString,
            ),
            'SubmitOperationalTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOperationalTransaction,
                    request_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitOperationalTransactionRequest.FromString,
                    response_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitOperationalTransactionResponse.SerializeToString,
            ),
            'QueryTransactionState': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTransactionState,
                    request_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryTransactionStateRequest.FromString,
                    response_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryTransactionStateResponse.SerializeToString,
            ),
            'QueryAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAccount,
                    request_deserializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryAccountRequest.FromString,
                    response_serializer=google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.universalledger.v1.UniversalLedger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.cloud.universalledger.v1.UniversalLedger', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UniversalLedger:
    """A service for interacting with the Google Cloud Universal Ledger.
    Endpoints are pre-created and managed by Google and cannot
    be modified by users.
    The names of available endpoints will be provided in the public
    documentation.
    An endpoint is a regional resource within a Universal Ledger network.
    Requests sent to an endpoint may be routed to different validators in the
    given network within the given region.
    """

    @staticmethod
    def SubmitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.universalledger.v1.UniversalLedger/SubmitTransaction',
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitTransactionRequest.SerializeToString,
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEndpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.universalledger.v1.UniversalLedger/ListEndpoints',
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.ListEndpointsRequest.SerializeToString,
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.ListEndpointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEndpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.universalledger.v1.UniversalLedger/GetEndpoint',
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.GetEndpointRequest.SerializeToString,
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.Endpoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitOperationalTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.universalledger.v1.UniversalLedger/SubmitOperationalTransaction',
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitOperationalTransactionRequest.SerializeToString,
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.SubmitOperationalTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTransactionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.universalledger.v1.UniversalLedger/QueryTransactionState',
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryTransactionStateRequest.SerializeToString,
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryTransactionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.universalledger.v1.UniversalLedger/QueryAccount',
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryAccountRequest.SerializeToString,
            google_dot_cloud_dot_universalledger_dot_v1_dot_universalledger__pb2.QueryAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
